=== BBN-E/Adept/adept-api/src/main/resources/adept/io/AWAKE.xsd
<!--Copyright 2014  Raytheon BBN Technologies Corp. All Rights Reserved. -->

<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="document">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="passage" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="corpus_id" type="xs:string" use="optional"/>
			<xs:attribute name="corpus_name" type="xs:string" use="optional"/>
			<xs:attribute name="corpus_type" type="xs:string" use="optional"/>
			<xs:attribute name="document_capture_date" type="xs:dateTime" use="required"/>
			<xs:attribute name="document_genre" type="xs:string" use="optional"/>
			<xs:attribute name="document_headline" type="xs:string" use="optional"/>
			<xs:attribute name="document_id" type="xs:unsignedLong" use="required"/>
			<xs:attribute name="document_language" type="xs:string" use="optional"/>
			<xs:attribute name="document_name" type="xs:string" use="required"/>
			<xs:attribute name="document_publication_date" type="xs:dateTime" use="optional"/>
			<xs:attribute name="document_split_id" type="xs:unsignedLong" use="required"/>
			<xs:attribute name="document_type" type="xs:string" use="optional"/>
			<xs:attribute name="document_uri" type="xs:string" use="optional"/>
			<xs:attribute name="source_uri" type="xs:string" use="optional"/>
			<xs:attribute name="source_language" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[a-z][a-z]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="passage_content">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"/>
			<xs:maxLength value="40000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="passage">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="passage_content">
					<xs:attribute name="passage_duration" type="xs:decimal" use="optional"/>
					<xs:attribute name="passage_id" type="xs:unsignedLong" use="required"/>
					<xs:attribute name="passage_start_offset" type="xs:decimal" use="optional"/>
					<xs:attribute name="speaker" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BBN-E/Adept/adept-api/src/test/resources/adept/io/awakeTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright 2012-2017 Raytheon BBN Technologies Corp. All Rights Reserved. -->
<document document_name="albawaba_news_242533" document_type="text" document_genre="news" source_language="en" document_capture_date="2009-04-08T14:39:45.000000+00:00" 
document_language="English" document_id="12345" document_split_id="0" document_headline="Lebanon approves first Syrian ambassador" document_uri="http://www.albawaba.com/en/news/242533" corpus_id="222" corpus_name="albawaba_news" corpus_type="website"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="\\mercury-04\u39\DEFT\users\jwatson\sandbox\deft\adept\adept-api\src\test\resources\adept\io\AWAKE.xsd" >
	<passage passage_id="1" >Lebanon approves first Syrian ambassador

	</passage>
	<passage passage_id="2" >Posted: 24-03-2009 , 13:31 GMT

	</passage>
	<passage passage_id="3" >Lebanon approved on Tuesday Syria's nominee for its first ambassador to Beirut, five months after the two countries established diplomatic ties for the first time, an official said.
	
	</passage>
	<passage passage_id="4" >"President Michel Sleiman on Tuesday approved the nomination of Ali Abdel Karim Ali as the Syrian Arab Republic's ambassador to Beirut," the official in the president's office said, according to AFP .
	
	</passage>
	<passage passage_id="5" >Lebanon's ambassador to Damascus, diplomat Michel el-Khoury, was named at the start of the year and an embassy was opened in the Syrian capital earlier this month.
	
	</passage>
	<passage passage_id="6" >The 56 year old Ali has been ambassador to Kuwait since November 2004 and has also served as the head of Syrian state radio and television and the official SANA news agency. In 1998, the married father of four published a collection of poems.
	
	</passage>
	<passage passage_id="7" >© 2009 Al Bawaba (www.albawaba.com)
	
	</passage>
	<passage passage_id="8" >Opinions - No Opinions found for this article Document Date: 2009-04-08" 

</passage>
<!-- test error cases -->
	<passage passage_id="9" ></passage>
	<passage passage_id="10" >قد غير زهاء لكون الخاسرة, انه عن الحكومة الضحايا. مرمى عرفها وصافرات عام أن. بل انه سليمان، الإحتلال, قِبل التحالف الأهداف وفي هو, اقتصّت والنرويج اليابانية قصف أن. الحروب باحتلال البشريةً و يبق, بها ٣٠ وسفن وسوء الساحل. تشكيل قائمة يتسنّى كلّ هو</passage>
	<passage passage_id="11" > 	 	 	</passage>
	<passage passage_id="20" >This one skips an ID" </passage>
</document>
